apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: drupalcntr
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: drupalcntr
    spec:
      containers:
      - name: pdtacr
        image: docker.io/drupal
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-auth


---
apiVersion: v1
kind: Service
metadata:
  name: drupalcntr
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: drupalcntr
